services:
  backend:
    image: 'mycardetails:latest'
    restart: unless-stopped
    build:
      context: .
      dockerfile: Backend/Dockerfile
    container_name: mycardetails_backend
    environment:
      - SPRING_DATASOURCE_URL=${SQL_URL}
      - SPRING_DATASOURCE_USERNAME=${SQL_USER}
      - SPRING_DATASOURCE_PASSWORD=${SQL_PASS}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - JWT=${JWT}
    ports:
      - 8080:8080
    extra_hosts:
      - "host.docker.internal:host-gateway"
          
  frontend:
    image: 'mycardetails_frontend:latest'
    build:
      context: .
      dockerfile: Frontend/Dockerfile
    container_name: mycardetails_frontend
    depends_on:
      - backend
    ports:
      - 80:80
