name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: [self-hosted]

    steps:
    - name: Standard Checkout
      uses: actions/checkout@v2
    - name: Package
      run: mvn clean package -Dmaven.test.skip
      working-directory: _work/MyCarDetails_ELTE/MyCarDetails_ELTE/Backend/
    - name: Build the Docker image
      env:
          SQL_URL: ${{ secrets.SQL_URL }}
          SQL_USER: ${{ secrets.SQL_USER }}
          SQL_PASS: ${{ secrets.SQL_PASS }}
          JWT: ${{ secrets.JWT }}
      run: sudo docker build . --file Backend/Dockerfile --tag mycardetails:latest
