name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: [self-hosted]

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      env:
          SQL_URL: ${{ secrets.SQL_URL }}
          SQL_USER: ${{ secrets.SQL_USER }}
          SQL_PASS: ${{ secrets.SQL_PASS }}
          JWT: ${{ secrets.JWT }}
      run: sudo docker build \
        --file Backend/Dockerfile \
        --tag my-image-name:$(date +%s) \
        --build-arg SQL_URL=${SQL_URL} \
        --build-arg SQL_USER=${SQL_USER} \
        --build-arg SQL_PASS=${SQL_PASS} \
        --build-arg JWT=${JWT} \
        .
