name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: [self-hosted]

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      env:
          SQL_URL: ${{ secrets.SQL_URL }}
          SQL_USER: ${{ secrets.SQL_USER }}
          SQL_PASS: ${{ secrets.SQL_PASS }}
          JWT: ${{ secrets.JWT }}
      #run: sudo docker build . --file Backend/Dockerfile --tag my-image-name:$(date +%s)
      run: echo 1
    - name: Debug Environment Variables
      run: |
        echo "SgQL_URL: ${{ secrets.SQL_URL }}"
        echo "SQL_USER: ${{ secrets.SQL_USER }}"
        echo "JWT: ${{ secrets.JWT }}"
