name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: [self-hosted]

    steps:
    - name: Set environment variables
      env:
          SQL_URL: ${{ secrets.SQL_URL }}
          SQL_USER: ${{ secrets.SQL_USER }}
          SQL_PASS: ${{ secrets.SQL_PASS }}
          JWT: ${{ secrets.JWT }}
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: sudo docker build . --file Backend/Dockerfile --tag my-image-name:$(date +%s)
