name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: [self-hosted]

    steps:
    - name: Standard Checkout
      uses: actions/checkout@v2
    - name: Package
      run: mvn clean package -Dmaven.test.skip
      working-directory: Backend/
    - name: Build the Docker image
      env:
          SQL_URL: ${{ secrets.SQL_URL }}
          SQL_USER: ${{ secrets.SQL_USER }}
          SQL_PASS: ${{ secrets.SQL_PASS }}
          JWT: ${{ secrets.JWT }}
      run: sudo docker build . --file Backend/Dockerfile --tag mycardetails:latest
    - name: Run Docker container
      env:
          SQL_URL: ${{ secrets.SQL_URL }}
          SQL_USER: ${{ secrets.SQL_USER }}
          SQL_PASS: ${{ secrets.SQL_PASS }}
          JWT: ${{ secrets.JWT }}
      run: sudo docker run -d -p 8080:8080 -e SQL_USER=${{ secrets.SQL_USER }} -e SQL_PASS=${{ secrets.SQL_PASS }} -e SQL_URL=${{ secrets.SQL_URL }} -e JWT=${{ secrets.JWT }} mycardetails
