name: Docker Image CI

on:
  push:
    branches: [ "release" ]

jobs:
  build:
    runs-on: [self-hosted]

    steps:
    - name: Standard Checkout
      uses: actions/checkout@v2

    - name: Package Backend
      run: mvn clean package -Dmaven.test.skip
      working-directory: Backend/

    - name: Build and Run with Docker Compose
      env:
        SQL_URL: ${{ secrets.SQL_URL }}
        SQL_USER: ${{ secrets.SQL_USER }}
        SQL_PASS: ${{ secrets.SQL_PASS }}
        JWT: ${{ secrets.JWT }}
      run: docker compose up --build -d
